### ISSUE TITLE
can't load elevation/saved_models/aggregation_model.pkl

### ISSUE THREAD

**Issue by desertzk** [microsoft/Elevation#5]
Hi
when i run demo 2, Aggregation Prediction,i encountered some problem in this line.
final_model, other = pickle.load(fh)
Traceback (most recent call last):
  File "/home/zk/myresearch/Elevation/learnaggr.py", line 24, in <module>
    final_model, other = pickle.load(fh)
  File "/home/zk/anaconda3/envs/elevation27/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/zk/anaconda3/envs/elevation27/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: 'v'

can some one help me thanks

**Comment by dmaljovec** [comment]
I am having similar issues with this particular model. Is there a way to regenerate this pickle file locally? I see it referenced in one of the notebooks (`aggregations.ipynb`) however that seems to reference files that we do not have access to.

**Comment by dmaljovec** [comment]
Looking at another issue #2, this comment seems relevant:

> Sometimes the 'git clone' command does not copy pickle files properly. So I checked the size of all pickle files and downloaded manually if the files were damaged.

I checked my repo and sure enough this files was only 130 bytes, whereas the actual file is supposed to be 88 KB. I don't know if this was due to my own manipulation or the cloning issue mentioned above. I manually downloaded the file using:

```
wget https://github.com/microsoft/Elevation/raw/master/elevation/saved_models/aggregation_model.pkl
```

And it appears my file is now the correct size at least. 🤷
